version: "3.8"

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: docker.io/bitnami/postgresql:16.0.0
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=email-dispatch-gateway
      - POSTGRESQL_LOG_TIMEZONE=GMT
      - POSTGRESQL_TIMEZONE=GMT

  keycloak:
    image: docker.io/bitnami/keycloak:22.0.3
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=user
      - KEYCLOAK_ADMIN_PASSWORD=bitnami
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_JDBC_PARAMS=useSSL=false

  server:
    container_name: server
    build:
      context: .
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - keycloak
      - postgres
