### POST /campaigns
# @no-log
POST {{baseURL}}/campaigns
Content-Type: application/json
Authorization: Bearer {{kc_B2B_accessToken}}

{
  "name": "Campaign Name",
  "content": "Campaign Content",
  "emails": [
    "email_a@domain.com",
    "email_b@domain.com",
    "email_c@domain.com"
  ]
}

> {% client.global.set("campaignId", response.body["id"]) %}


### GET /campaigns/:id
# @no-log
GET {{baseURL}}/campaigns/{{campaignId}}
Authorization: Bearer {{kc_B2C_accessToken}}


### PATCH /campaigns/:id/cancel
# @no-log
PATCH {{baseURL}}/campaigns/{{campaignId}}/cancel
Authorization: Bearer {{kc_B2B_accessToken}}


### DELETE /campaigns/:id
# @no-log
DELETE {{baseURL}}/campaigns/{{campaignId}}
Authorization: Bearer {{kc_B2B_accessToken}}

--- Health

### GET /health
# @no-log
GET {{baseURL}}/health

--- KEYCLOAK


### Credtentials B2B
# @no-log
POST {{kc_baseURL}}/realms/{{kc_Realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=email-dispatch-gateway&
client_secret={{kc_B2B_localClientSecret}}&
grant_type=client_credentials

> {% client.global.set("kc_B2B_accessToken", response.body["access_token"]) %}


### Credtentials B2C
# @no-log
POST {{kc_baseURL}}/realms/{{kc_Realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=email-dispatch-gateway-users&
username={{kc_B2C_localUsername}}&
password={{lc_B2C_localPassword}}&
grant_type=password

> {% client.global.set("kc_B2C_accessToken", response.body["access_token"]) %}
