### POST /campaigns
# @no-log
POST {{baseURL}}/campaigns
Content-Type: application/json

{
  "name": "Campaign Name",
  "content": "Campaign Content",
  "emails": [
    "email_a@domain.com",
    "email_b@domain.com",
    "email_c@domain.com"
  ]
}

> {% client.global.set("campaignId", response.body["id"]) %}


### GET /campaigns/:id
# @no-log
GET {{baseURL}}/campaigns/{{campaignId}}


### PATCH /campaigns/:id/cancel
# @no-log
PATCH {{baseURL}}/campaigns/{{campaignId}}/cancel


### DELETE /campaigns/:id
# @no-log
DELETE {{baseURL}}/campaigns/{{campaignId}}
